version = "0.2"
language = "en"
words = [
  "bindgen",
  "bunfig",
  "bunx",
  "extralight",
  "fontawesome",
  "fonticons",
  "footgun",
  "geschwendt",
  "hyperlegible",
  "instrumenter",
  "jgeschwendt",
  "msrv",
  "navigations",
  "networkidle",
  "npmjs",
  "prerendered",
  "résumé",
  "rockethomes",
  "rustup",
  "sitefinity",
  "springthrough",
  "symfony",
  "tailwindcss",
  "turbopack",
  "winit",
]
