import { config as defineConfig } from '@jlg/eslint';
import next from '@next/eslint-plugin-next';

const config = defineConfig(
  {},
  next.configs['core-web-vitals'],
  {
    // public/background: wasm-bindgen output, regenerated by `bun run background:build`.
    ignores: ['.next', 'next-env.d.ts', 'public/background'],
  },
  {
    files: ['src/components/icons/Icons.tsx'],
    rules: {
      '@typescript-eslint/no-magic-numbers': 'off',
      'import/group-exports': 'off',
      'react/jsx-props-no-spreading': 'off',
      'react/no-multi-comp': 'off',
    },
  },
  {
    files: ['scripts/**/*.ts'],
    rules: {
      '@typescript-eslint/no-magic-numbers': 'off',
      'import/no-nodejs-modules': 'off',
      'no-await-in-loop': 'off',
      'no-console': 'off',
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parserOptions: {
        tsconfigRootDir: import.meta.dirname,
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
      reportUnusedInlineConfigs: 'error',
    },
    rules: {
      '@typescript-eslint/prefer-readonly-parameter-types': 'off',
      'import/no-internal-modules': [
        'warn',
        {
          allow: [
            'motion/react',
            'next/font/google',
            'next/headers',
            'next/image',
            'next/link',
            'next/navigation',
            'next/server',
          ],
        },
      ],
      'import/no-unassigned-import': [
        'warn',
        {
          allow: ['@/app/global.css'],
        },
      ],
    },
  },
  {
    files: ['**/*.tsx'],
    rules: {
      'id-length': ['error', { exceptions: ['x', 'y'] }],
      'react/forbid-component-props': [
        'error',
        {
          forbid: ['style', { allowedFor: ['Link'], propName: 'className' }],
        },
      ],
      'react/jsx-max-depth': ['error', { max: 7 }],
      'unicorn/filename-case': ['error', { case: 'pascalCase' }],
    },
  },
  {
    files: ['src/proxy.ts', '**/server/proxy/index.ts', '**/default.tsx'],
    rules: {
      'import/no-default-export': 'off',
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      'max-statements': 'off',
    },
  },
  {
    files: ['src/app/resume/Resume.tsx'],
    rules: {
      'react/jsx-curly-brace-presence': 'off',
      'react/jsx-no-literals': 'off',
    },
  },
);

export default config;
