import base from '@jlg/oxfmt' with { type: 'json' };

// The @jgeschwendt/oxfmt base (as of 0.2.0: only `singleQuote`) is spread in LIVE
// — imported straight from the package, not copied. oxfmt has no `extends`, but it
// DOES auto-discover this `oxfmt.config.ts` in the repo root (verified 2026-07-22,
// oxfmt 0.59 — no `-c` needed at any invocation site) and evaluates it under Node.
// printWidth is intentionally omitted — this repo predates the base's former 80
// imposition and uses oxfmt's default (100).
export default {
  ...base,
  // public/background: wasm-bindgen output, regenerated by `bun run
  // background:build` — never hand-format it. .vscode: editor settings.
  ignorePatterns: ['.vscode/**', 'public/background/**'],
  sortTailwindcss: {
    stylesheet: './src/app/global.css',
  },
};
