import { defineConfig } from '@jlg/oxfmt';

// defineConfig shallow-merges the @jgeschwendt/oxfmt base (only `singleQuote`)
// under these local keys (base first, local wins). oxfmt has no `extends`, but it
// DOES auto-discover this `oxfmt.config.ts` in the repo root (verified 2026-07-22,
// oxfmt 0.59 — no `-c` needed at any invocation site) and evaluates it under Node.
// printWidth is intentionally omitted — this repo predates the base's former 80
// imposition and uses oxfmt's default (100).
// stele:landmark format-policy
export default defineConfig({
  // public/background: wasm-bindgen output, regenerated by `bun run
  // background:build` — never hand-format it. .vscode: editor settings.
  // .stele: stele-emitted graph index/router markdown — oxfmt would reflow the
  // generated tables and fight `stele emit --check`.
  ignorePatterns: ['.stele/**', '.vscode/**', 'public/background/**'],
  sortTailwindcss: {
    stylesheet: './src/app/global.css',
  },
});
