import { fibonacci } from '../lib';

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 *   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
describe('Problem 2', () => {
  const solution = (limit: number): number => (
    fibonacci(limit)
      .filter((n) => (n % 2 === 0))
      .reduce((t, n) => (t + n), 0)
  );

  test('Even Fibonacci numbers', () => {
    expect(solution(4000000)).toBe(4613732);
  });
});
