name: ci

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.event.pull_request.number || github.ref }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - run: bun install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: bunx prettier --check .
      - run: bun run lint
      - run: bun run build
